import { CreateExerciseDTO } from '../dtos/create-exercise.dto'
import { IExerciseRepository } from '@application/ports/exercise-repository.port'
import { Category } from '@domain/shared/value-objects/category'
import { Exercise } from '@domain/exercise/exercise.entity'
import { ExerciseResponseDTO } from '../dtos/exercise-response.dto'

export class CreateExerciseUseCase {
  constructor(private readonly exerciseRepository: IExerciseRepository) {}

  async execute(dto: CreateExerciseDTO): Promise<ExerciseResponseDTO> {
    const category = Category.create(dto.category)
    const exercise = Exercise.create({
      id: 0, // Will be auto-generated by database
      name: dto.name,
      category
    })
    const createdExercise = await this.exerciseRepository.create(exercise)

    return createdExercise.toJSON()
  }
}
