packages:
  - apps/*
  - packages/*

catalogs:
  main:
    typescript: ^5.9.2
    eslint: ^9.23.0
    prettier: ^3.5.3
    '@types/node': ^24.7.0
    zod: ^4.1.12
  prisma:
    prisma: latest
    '@prisma/client': 7.2.0
  react:
    react: 19.2.3
    react-dom: 19.2.0
    '@types/react': ^19.2.8
    '@types/react-dom': ^19.2.3
  next:
    next: 16.1.2
    eslint-config-next: 16.1.2

nodeLinker: hoisted
