import { IRoutineRepository } from '@application/ports/routine-repository.port'
import { CreateRoutineDTO } from '../dtos/create-routine.dto'
import { RoutineResponseDTO } from '../dtos/routine-response.dto'
import { Category } from '@domain/shared/value-objects/category'
import { Routine } from '@domain/routine/routine.entity'

export class CreateRoutineUseCase {
  constructor(private readonly routineRepository: IRoutineRepository) {}

  async execute(dto: CreateRoutineDTO): Promise<RoutineResponseDTO> {
    const category = Category.create(dto.category)

    const routine = Routine.create({
      id: 0, // Will be auto-generated by database
      userId: dto.userId,
      name: dto.name,
      category,
      description: dto.description
    })

    const createdRoutine = await this.routineRepository.create(routine)

    // If exerciseIds provided, add them to the routine
    if (dto.exerciseIds && dto.exerciseIds.length > 0) {
      await this.routineRepository.addExercisesToRoutine(
        createdRoutine.id,
        dto.exerciseIds
      )
    }

    return createdRoutine.toJSON()
  }
}
