services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: gymter-database
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - '5432:5432'
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
